name: Daily Commit

on:
  schedule:
    - cron: "9 12 * * *"   # 5:39 PM IST
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Make changes
        run: |
          echo "Day $(date +%j): Streak maintained 🔥" >> log.txt

      - name: Commit & Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Daily auto commit ✨" || echo "No changes"
          git push origin main || echo "Push failed"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
