name: Daily Commit

on:
  schedule:
    - cron: "0 18 * * *"   # 11:30 PM IST (adjust if needed)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Make changes
        run: |
          echo "Day $(date +%j): Streak maintained 🔥" >> log.txt

      - name: Commit & Push
        run: |
          git config --global user.name "Anurag"
          git config --global user.email "anuraggaur29@gmail.com"
          git add .
          git commit -m "Daily auto commit ✨"
          git push
